//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class AssignDelivery
    {
        public int EmployeeID { get; set; }
        public int DeliveryID { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]
        [DisplayName("Assigned Date")]
        public System.DateTime DateAssigned { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
