//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class AuditLog
    {
        public int AuditLogID { get; set; }
        
        [DisplayName("Date Accessed")]
        public System.DateTime DateAccessed { get; set; }

        
        [DisplayName("Table Accessed")]
        public string TableAccessed { get; set; }
        
        [DisplayName("Change Made")]
        public string ChangesMade { get; set; }
        public int AuditLogTypeID { get; set; }
        public int UserID { get; set; }
    
        public virtual AuditLogType AuditLogType { get; set; }
        public virtual User User { get; set; }
    }
}
