//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckEquipmentLine
    {
        public int EquipmentID { get; set; }
        public int CheckEquipmetStatusID { get; set; }
        public int CheckEquipmentID { get; set; }
    
        public virtual CheckEquipment CheckEquipment { get; set; }
        public virtual CheckEquipmentStatu CheckEquipmentStatu { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
