//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientFeedback
    {
        public int ClientFeedBackID { get; set; }
        public int Profesionalism { get; set; }
        public int Cleanliness { get; set; }
        public Nullable<int> Friendliness { get; set; }
        public Nullable<int> Punctuality { get; set; }
        public Nullable<int> ServiceQuality { get; set; }
        public int ClientID { get; set; }
        public string Comment { get; set; }
        public int ServiceRequestID { get; set; }
    
        public virtual ServiceRequest ServiceRequest { get; set; }
    }
}
