//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delivery()
        {
            this.AssignDeliveries = new HashSet<AssignDelivery>();
            this.DeliveryLines = new HashSet<DeliveryLine>();
        }
    
        public int DeliveryID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Date)]
        [DisplayName("Date of Delivery")]
        public System.DateTime DateOfDelivery { get; set; }
        public int DeliveryStatusID { get; set; }
        public int ProductOrderID { get; set; }
        
        [DisplayName(" Client Signature")]
        public byte[] DeliverySignature { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignDelivery> AssignDeliveries { get; set; }
        public virtual DeliveryStatu DeliveryStatu { get; set; }
        public virtual ProductOrder ProductOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryLine> DeliveryLines { get; set; }
    }
}
