//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductOrderLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductOrderLine()
        {
            this.ProductOrderReturnLines = new HashSet<ProductOrderReturnLine>();
        }

        [DataType(DataType.Currency)]
        [DisplayName("Selling Price")]
        public double Selling_Price { get; set; }
        [DisplayName("Quantity Ordered")]

        public int QuantityOrdered { get; set; }
        [DisplayName("Quantity Delivered")]
        public int QuantityDelivered { get; set; }
        [DataType(DataType.Date)]
        [DisplayName("Order Date")]
        public System.DateTime OrderDate { get; set; }
        public int ProductID { get; set; }
        public int ProductOrderID { get; set; }

        public virtual Product Product { get; set; }
        public virtual ProductOrder ProductOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOrderReturnLine> ProductOrderReturnLines { get; set; }
    }
}
