//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.ServiceLines = new HashSet<ServiceLine>();
        }

        public int ServiceID { get; set; }
        [DataType(DataType.Text)]
        [DisplayName("Name of Service")]
        public string Name { get; set; }
        [DataType(DataType.Text)]
        [DisplayName("Description of Service")]
        public string Description { get; set; }
        public int ServiceRequestID { get; set; }
        public int ServiceItemID { get; set; }

        public virtual ServiceItem ServiceItem { get; set; }
        public virtual ServiceRequest ServiceRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceLine> ServiceLines { get; set; }
    }
}
