//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceRequest()
        {
            this.ClientFeedbacks = new HashSet<ClientFeedback>();
            this.Complaints = new HashSet<Complaint>();
            this.EmployeeRequests = new HashSet<EmployeeRequest>();
            this.Services = new HashSet<Service>();
        }
    
        public int ServiceRequestID { get; set; }
        public int ServiceRequestStatusID { get; set; }
        public System.DateTime ServiceRequestDate { get; set; }
        public System.DateTime ServiceBookedDate { get; set; }
        public Nullable<System.DateTime> ServiceBookedEndDate { get; set; }
        public string Comment { get; set; }
        public int LocationID { get; set; }
        public Nullable<bool> IsFullDay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientFeedback> ClientFeedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint> Complaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeRequest> EmployeeRequests { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Services { get; set; }
        public virtual ServiceRequestStatu ServiceRequestStatu { get; set; }
    }
}
