//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class mvcAssignDeliveryModel
    {
        public int EmployeeID { get; set; }
        public int DeliveryID { get; set; }
        [Required(ErrorMessage ="This field is required")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime DateAssigned { get; set; }
    
        public virtual mvcDeliveryModel Delivery { get; set; }
        public virtual mvcEmployeeModel Employee { get; set; }
    }
}
