//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mvcAuditLogModel
    {
        public int AuditLogID { get; set; }
        public System.DateTime DateAccessed { get; set; }
        public string TableAccessed { get; set; }
        public string InformationChanged { get; set; }
        public string NewInformationEntered { get; set; }
        public int AuditLogTypeID { get; set; }
        public int UserID { get; set; }
    
        public virtual mvcAuditLogTypeModel AuditLogType { get; set; }
        public virtual mvcUserModel User { get; set; }
    }
}
