//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class mvcCompanyInfoModel
    {
        public int CompanyID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Text)]
        public string CompanyName { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string CompanyAddress { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string CompanyEmailAddress { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string TelephoneNumber { get; set; }
        public int ClientID { get; set; }
    
        public virtual mvcClientModel Client { get; set; }
    }
}
