//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class mvcComplaintModel
    {
        public int ComplaintID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string Description { get; set; }
        public int ClientID { get; set; }
        public int ServiceRequestID { get; set; }
    
        public virtual mvcClientModel Client { get; set; }
        public virtual mvcServiceRequestModel ServiceRequest { get; set; }
    }
}
