//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class mvcCheckEquipmentModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mvcCheckEquipmentModel()
        {
            this.CheckEquipmentLines = new HashSet<mvcCheckEquipmentLineModel>();
        }
    
        public int CheckEquipmentID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public System.DateTime DateChecked { get; set; }
        public int VehicleID { get; set; }
    
        public virtual mvcVehicleModel Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvcCheckEquipmentLineModel> CheckEquipmentLines { get; set; }
    }
}
