//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mvcCheckEquipmentLineModel
    {
        public int EquipmentID { get; set; }
        public int CheckEquipmetStatusID { get; set; }
        public int CheckEquipmentID { get; set; }
    
        public virtual mvcCheckEquipmentModel CheckEquipment { get; set; }
        public virtual mvcCheckEquipmentStatuModel CheckEquipmentStatu { get; set; }
        public virtual mvcEquipmentModel Equipment { get; set; }
    }
}
