//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class mvcDeliveryModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mvcDeliveryModel()
        {
            this.AssignDeliveries = new HashSet<mvcAssignDeliveryModel>();
        }
    
        public int DeliveryID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public System.DateTime DateOfDelivery { get; set; }
        public int DeliveryStatusID { get; set; }
        public int ProductOrderID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvcAssignDeliveryModel> AssignDeliveries { get; set; }
        public virtual mvcDeliveryStatuModel DeliveryStatu { get; set; }
    }
}
