//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class mvcLocationModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mvcLocationModel()
        {
            this.ServiceRequests = new HashSet<mvcServiceRequestModel>();
        }
    
        public int LocationID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Street Address")]
        public string StreetAddress { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Suburb")]
        public string Suburb { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("City")]
        public string City { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Postal Code")]
        public string PostalCode { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Contact Name")]
        public string ContactPersonName { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Contact Number")]
        public string ContactPersonNumber { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public int LocationTypeID { get; set; }
        public int ClientID { get; set; }
    
        public virtual mvcClientModel Client { get; set; }
        public virtual mvcLocationTypeModel LocationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvcServiceRequestModel> ServiceRequests { get; set; }
        public List<Location> LocationList { get; set; }
        public List<LocationType> LocationTypeList { get; set; }
        public List<Client> ClientList { get; set; }
        public Location emp { get; set; }
    }
}
