//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mvcProductOrderLineModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mvcProductOrderLineModel()
        {
            this.ProductOrderReturnLines = new HashSet<mvcProductOrderReturnLineModel>();
        }
    
        public double Selling_Price { get; set; }
        public int QuantityOrdered { get; set; }
        public int QuantityDelivered { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int ProductID { get; set; }
        public int ProductOrderID { get; set; }
    
        public virtual mvcProductModel Product { get; set; }
        public virtual mvcProductOrderModel ProductOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvcProductOrderReturnLineModel> ProductOrderReturnLines { get; set; }
    }
}
