//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class mvcProductOrderModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mvcProductOrderModel()
        {
            this.ProductOrderLines = new HashSet<mvcProductOrderLineModel>();
        }
    
        public int ProductOrderID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public System.DateTime DateOfOrder { get; set; }
        public int ProductOrderStatusID { get; set; }
        public int Client_ID { get; set; }
    
        public virtual mvcClientModel Client { get; set; }
        public virtual mvcProductOrderStatuModel ProductOrderStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvcProductOrderLineModel> ProductOrderLines { get; set; }
    }
}
