//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class mvcProductModel
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mvcProductModel()
        {
            this.ProductOrderLines = new HashSet<mvcProductOrderLineModel>();
            this.ServiceLines = new HashSet<mvcServiceLineModel>();
            this.SupplierOrderLines = new HashSet<mvcSupplierOrderLineModel>();
            this.WriteOfProducts = new HashSet<mvcWriteOfProductModel>();
        }

        public int ProductID { get; set; }
        public string Name { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string Description { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public int QuantityOnHand { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public System.DateTime ExpiryDate { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public double SellingPrice { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public int ProductStatusID { get; set; }
        public int ProductTypeID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public int MinimumQuantity { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string Dscription { get; set; }

        public virtual mvcProductStatuModel ProductStatu { get; set; }
        public virtual mvcProductTypeModel ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvcProductOrderLineModel> ProductOrderLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvcServiceLineModel> ServiceLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvcSupplierOrderLineModel> SupplierOrderLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvcWriteOfProductModel> WriteOfProducts { get; set; }
        public int UserRoleId { get; set; }
    }
}
