//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class mvcServiceModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mvcServiceModel()
        {
            this.ServiceLines = new HashSet<mvcServiceLineModel>();
        }
    
        public int ServiceID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Description")]
        public string Description { get; set; }

        public int ServiceRequestID { get; set; }
        public int ServiceItemID { get; set; }
    
        public virtual mvcServiceRequestModel ServiceRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvcServiceLineModel> ServiceLines { get; set; }
    }
}
