//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mvcSupplierOrderModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mvcSupplierOrderModel()
        {
            this.SupplierOrderLines = new HashSet<mvcSupplierOrderLineModel>();
        }
    
        public int SupplierOrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int SupplierStatusID { get; set; }
        public int SupplierID { get; set; }
    
        public virtual mvcSupplierModel Supplier { get; set; }
        public virtual mvcSupplierStatuModel SupplierStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvcSupplierOrderLineModel> SupplierOrderLines { get; set; }
        public int UserRoleId { get; set; }
    }
}
