//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class mvcSupplierModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mvcSupplierModel()
        {
            this.SupplierOrders = new HashSet<mvcSupplierOrderModel>();
        }
    
        public int SupplierID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Contact Name")]
        public string ContactPersonName { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Contact Surname")]
        public string ContactPersonSurname { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Contact Number")]
        public string ContactNumber { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Email Address")]
        public string EmailAddress { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Registration Number")]
        public string RegistrationNumber { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Credit Balance")]
        public double CreditBalance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvcSupplierOrderModel> SupplierOrders { get; set; }
        public int UserRoleId { get; set; }
    }
}
