//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class mvcServiceItemModel
    {
        public int ServiceItemID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public int itemNumber { get; set; }
        public int WorkDoneID { get; set; }
        public int ServiceItemSizeID { get; set; }
        public int ServiceItemTypeID { get; set; }
    
        public virtual mvcServiceItemSizeModel ServiceItemSize { get; set; }
        public virtual mvcServiceItemTypeModel ServiceItemType { get; set; }
        public virtual mvcWorkDoneModel WorkDone { get; set; }
    }
}
