//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mvcSupplierOrderReturnModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mvcSupplierOrderReturnModel()
        {
            this.SupplierOrderReturnLines = new HashSet<mvcSupplierOrderReturnLineModel>();
        }
    
        public int ReturnID { get; set; }
        public System.DateTime ReturnDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvcSupplierOrderReturnLineModel> SupplierOrderReturnLines { get; set; }
    }
}
