//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class mvcUserModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mvcUserModel()
        {
            this.AuditLogs = new HashSet<mvcAuditLogModel>();
            this.Clients = new HashSet<mvcClientModel>();
            this.Employees = new HashSet<mvcEmployeeModel>();
            this.Logins = new HashSet<mvcLoginModel>();
        }

        public int UserID { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("User Email:")]

        public string UserEmail { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("User Password:")]
        [DataType(DataType.Password)]
        public string UserPassword { get; set; }
        [NotMapped]

        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }

        [NotMapped]
        public string LoginErrorMessage { get; set; }

        public int UserRoleID { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvcAuditLogModel> AuditLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvcClientModel> Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvcEmployeeModel> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvcLoginModel> Logins { get; set; }

        public virtual IEnumerable<mvcUserRoleModel> UserRole { get; set; }
    }
}
