//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class mvcVATModel
    {
        public int VATID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public double VATRate { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public Nullable<System.DateTime> EffectiveDate { get; set; }
    }
}
