//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snow_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class mvcVehicleModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mvcVehicleModel()
        {
            this.CheckEquipments = new HashSet<mvcCheckEquipmentModel>();
        }
    
        public int VehicleID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Description")]
        public string Description { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("License Number")]
        public string LicenseNumber { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Purchase Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime PurchaseDate { get; set; }
        [DisplayName("Vehicle Type")]
        public int VehicleTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvcCheckEquipmentModel> CheckEquipments { get; set; }
        public virtual mvcVehicleTypeModel VehicleType { get; set; }
    }
}
