//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanFireWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int AuditLogID { get; set; }
        public System.DateTime DateAccessed { get; set; }
        public string TableAccessed { get; set; }
        public string ChangesMade { get; set; }
        public int AuditLogTypeID { get; set; }
        public int UserID { get; set; }
    
        public virtual AuditLogType AuditLogType { get; set; }
        public virtual User User { get; set; }
    }
}
