//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanFireWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int ComplaintID { get; set; }
        public string Description { get; set; }
        public int ClientID { get; set; }
        public int ServiceRequestID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ServiceRequest ServiceRequest { get; set; }
    }
}
