//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanFireWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryLine
    {
        public int DeliveryID { get; set; }
        public int ProductID { get; set; }
        public int ProductOrderID { get; set; }
        public int QuantitySent { get; set; }
    
        public virtual Delivery Delivery { get; set; }
    }
}
