//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanFireWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRequest
    {
        public int EmployeeID { get; set; }
        public int ServiceRequestID { get; set; }
        public System.DateTime DateAssigned { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ServiceRequest ServiceRequest { get; set; }
    }
}
