//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanFireWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrderReturnLine
    {
        public int ProductOrderID { get; set; }
        public int ProductOrderReturnID { get; set; }
        public int Quantity { get; set; }
        public string ReasonForReturn { get; set; }
        public int ProductID { get; set; }
    
        public virtual ProductOrderLine ProductOrderLine { get; set; }
        public virtual ProductOrderReturn ProductOrderReturn { get; set; }
    }
}
