//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanFireWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductOrderLines = new HashSet<ProductOrderLine>();
            this.ServiceLines = new HashSet<ServiceLine>();
            this.SupplierOrderLines = new HashSet<SupplierOrderLine>();
            this.WriteOfProducts = new HashSet<WriteOfProduct>();
        }
    
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string ProductDescription { get; set; }
        public int QuantityOnHand { get; set; }
        public double SellingPrice { get; set; }
        public int ProductStatusID { get; set; }
        public int ProductTypeID { get; set; }
        public int MinimumQuantity { get; set; }
    
        public virtual ProductStatu ProductStatu { get; set; }
        public virtual ProductType ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOrderLine> ProductOrderLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceLine> ServiceLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierOrderLine> SupplierOrderLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WriteOfProduct> WriteOfProducts { get; set; }
    }
}
