//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanFireWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierOrderLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierOrderLine()
        {
            this.SupplierOrderReturnLines = new HashSet<SupplierOrderReturnLine>();
        }
    
        public int QuantityOrdered { get; set; }
        public int QuantityReceived { get; set; }
        public int ProductPrice { get; set; }
        public int ProductID { get; set; }
        public int SupplierOrderID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SupplierOrder SupplierOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierOrderReturnLine> SupplierOrderReturnLines { get; set; }
    }
}
