//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanFireWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierOrderReturnLine
    {
        public int ReturnID { get; set; }
        public int SupplierOrderID { get; set; }
        public int ProductID { get; set; }
        public int QuantityReceived { get; set; }
        public string ReasonForReturn { get; set; }
        public int QuantityOrdered { get; set; }
    
        public virtual SupplierOrderLine SupplierOrderLine { get; set; }
        public virtual SupplierOrderReturn SupplierOrderReturn { get; set; }
    }
}
