//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanFireWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.CheckEquipments = new HashSet<CheckEquipment>();
        }
    
        public int VehicleID { get; set; }
        public string Description { get; set; }
        public string LicenseNumber { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int VehicleTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckEquipment> CheckEquipments { get; set; }
        public virtual VehicleType VehicleType { get; set; }
    }
}
