//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanFireWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WriteOfProduct
    {
        public int WriteOfID { get; set; }
        public int AmountWrittenOff { get; set; }
        public System.DateTime DateOfReturn { get; set; }
        public string ReasonForWriteOff { get; set; }
        public int ProductID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
